// 4 perros 
// 4 gatos
// 3 aves
// 1  tarantula
// 2 reptiles
// 1 tortuga


const animals = [
    {
        "especie": "Perro",
        "edad": "Adulto",
        "fechaDeNacimiento": "2019-03-10",
        "sexo": "Macho",
        "tamaño": "Grande",
        "peso": 25,
        "vacunado": true,
        "desparasitado": true,
        "sano": true,
        "esterilizado": true,
        "identificado": true,
        "microchip": true,
        "nombre": "Rocky",
        "image": "https://www.example.com/perro.jpg",
        "ubicacion": "Barcelona",
        "ciudad": "Barcelona",
        "personalidad": ["Amigable", "Activo", "Juguetón"],
        "historia": "Rescatado de la calle, busca un hogar amoroso.",
        "aSaber": "Le encanta correr y jugar al aire libre.",
        "requisitosAdopcion": "Necesita un hogar con espacio para correr y jugar.",
        "tasaAdopcion": 150,
        "seEnvia": "Adopciones locales únicamente",
        "adoptionState": "Disponible"
    },
    {
        "especie": "Perro",
        "edad": "Cachorro",
        "fechaDeNacimiento": "2023-01-10",
        "sexo": "Macho",
        "tamaño": "Pequeño",
        "peso": 5,
        "vacunado": false,
        "desparasitado": true,
        "sano": true,
        "esterilizado": false,
        "identificado": true,
        "microchip": false,
        "nombre": "Max",
        "image": "https://www.example.com/max.jpg",
        "ubicacion": "Barcelona",
        "ciudad": "Barcelona",
        "personalidad": ["Juguetón", "Curioso", "Amigable"],
        "historia": "Rescatado de la calle junto con sus hermanos.",
        "aSaber": "Tiene mucha energía y necesita jugar mucho.",
        "requisitosAdopcion": "Ideal para familias con niños o personas activas.",
        "tasaAdopcion": 200,
        "seEnvia": "Adopciones locales únicamente",
        "adoptionState": "Disponible"
    },
    {
        "especie": "Perro",
        "edad": "Adulto",
        "fechaDeNacimiento": "2017-03-20",
        "sexo": "Macho",
        "tamaño": "Grande",
        "peso": 20,
        "vacunado": true,
        "desparasitado": true,
        "sano": true,
        "esterilizado": true,
        "identificado": true,
        "microchip": true,
        "nombre": "Thor",
        "image": "https://www.example.com/thor.jpg",
        "ubicacion": "Valencia",
        "ciudad": "Valencia",
        "personalidad": ["Leal", "Protector", "Activo"],
        "historia": "Abandonado en un parque, necesita un hogar estable.",
        "aSaber": "Le encanta correr y jugar al aire libre.",
        "requisitosAdopcion": "Ideal para personas con experiencia en perros grandes.",
        "tasaAdopcion": 220,
        "seEnvia": "Adopciones locales únicamente",
        "adoptionState": "Disponible"
    },
    {
        "especie": "Gato",
        "edad": "Adulto",
        "fechaDeNacimiento": "2019-09-05",
        "sexo": "Hembra",
        "tamaño": "Mediano",
        "peso": 4,
        "vacunado": true,
        "desparasitado": true,
        "sano": true,
        "esterilizado": true,
        "identificado": true,
        "microchip": true,
        "nombre": "Luna",
        "image": "https://www.example.com/luna.jpg",
        "ubicacion": "Madrid",
        "ciudad": "Madrid",
        "personalidad": ["Cariñoso", "Tranquilo", "Curioso"],
        "historia": "Rescatado de la calle junto con sus hermanos.",
        "aSaber": "Le encanta dormir en lugares acogedores.",
        "requisitosAdopcion": "Ideal para hogares tranquilos.",
        "tasaAdopcion": 120,
        "seEnvia": "Adopciones locales únicamente",
        "adoptionState": "Disponible"
    },
    {
        "especie": "Gato",
        "edad": "Cachorro",
        "fechaDeNacimiento": "2023-02-15",
        "sexo": "Macho",
        "tamaño": "Pequeño",
        "peso": 2,
        "vacunado": false,
        "desparasitado": true,
        "sano": true,
        "esterilizado": false,
        "identificado": true,
        "microchip": false,
        "nombre": "Leo",
        "image": "https://www.example.com/leo.jpg",
        "ubicacion": "Barcelona",
        "ciudad": "Barcelona",
        "personalidad": ["Juguetón", "Curioso", "Sociable"],
        "historia": "Rescatado de un refugio, busca un hogar amoroso.",
        "aSaber": "Es muy cariñoso y le encanta jugar con pelotas.",
        "requisitosAdopcion": "Ideal para familias con niños o personas activas.",
        "tasaAdopcion": 150,
        "seEnvia": "Adopciones locales únicamente",
        "adoptionState": "Disponible"
    },
    {
        "especie": "Gato",
        "edad": "Adulto",
        "fechaDeNacimiento": "2018-05-20",
        "sexo": "Hembra",
        "tamaño": "Mediano",
        "peso": 3.5,
        "vacunado": true,
        "desparasitado": true,
        "sano": true,
        "esterilizado": true,
        "identificado": true,
        "microchip": true,
        "nombre": "Mia",
        "image": "https://www.example.com/mia.jpg",
        "ubicacion": "Valencia",
        "ciudad": "Valencia",
        "personalidad": ["Cariñosa", "Juguetona", "Tranquila"],
        "historia": "Rescatada de un hogar donde no podían cuidarla.",
        "aSaber": "Le gusta explorar y descansar en lugares altos.",
        "requisitosAdopcion": "Ideal para hogares con experiencia en gatos.",
        "tasaAdopcion": 130,
        "seEnvia": "Adopciones locales únicamente",
        "adoptionState": "Disponible"
    },
    {
        "especie": "Gato",
        "edad": "Cachorro",
        "fechaDeNacimiento": "2023-03-10",
        "sexo": "Hembra",
        "tamaño": "Pequeño",
        "peso": 2.5,
        "vacunado": false,
        "desparasitado": true,
        "sano": true,
        "esterilizado": false,
        "identificado": true,
        "microchip": false,
        "nombre": "Lola",
        "image": "https://www.example.com/lola.jpg",
        "ubicacion": "Sevilla",
        "ciudad": "Sevilla",
        "personalidad": ["Curiosa", "Energética", "Sociable"],
        "historia": "Rescatada de la calle junto con sus hermanos.",
        "aSaber": "Es muy juguetona y le encanta explorar nuevos lugares.",
        "requisitosAdopcion": "Ideal para familias con niños o personas activas.",
        "tasaAdopcion": 150,
        "seEnvia": "Adopciones locales únicamente",
        "adoptionState": "Disponible"
    },
    {
        "especie": "Ave",
        "edad": "Adulto",
        "fechaDeNacimiento": "2019-12-10",
        "sexo": "Macho",
        "tamaño": "Pequeño",
        "peso": 0.4,
        "vacunado": true,
        "desparasitado": true,
        "sano": true,
        "esterilizado": false,
        "identificado": true,
        "microchip": false,
        "nombre": "Paco",
        "image": "https://www.example.com/paco.jpg",
        "ubicacion": "Barcelona",
        "ciudad": "Barcelona",
        "personalidad": ["Alegre", "Sociable", "Juguetón"],
        "historia": "Rescatado de una situación de maltrato, busca un nuevo hogar.",
        "aSaber": "Le gusta cantar y estar en compañía.",
        "requisitosAdopcion": "Ideal para personas que puedan dedicarle tiempo y atención.",
        "tasaAdopcion": 100,
        "seEnvia": "Adopciones locales únicamente",
        "adoptionState": "Disponible"
    },
    {
        "especie": "Ave",
        "edad": "Adulto",
        "fechaDeNacimiento": "2020-02-20",
        "sexo": "Hembra",
        "tamaño": "Pequeño",
        "peso": 0.3,
        "vacunado": false,
        "desparasitado": true,
        "sano": true,
        "esterilizado": false,
        "identificado": true,
        "microchip": false,
        "nombre": "Lola",
        "image": "https://www.example.com/lola.jpg",
        "ubicacion": "Sevilla",
        "ciudad": "Sevilla",
        "personalidad": ["Tímida", "Cautelosa", "Curiosa"],
        "historia": "Rescatada de una situación de abandono, necesita un hogar tranquilo.",
        "aSaber": "Necesita tiempo para adaptarse a nuevos entornos y personas.",
        "requisitosAdopcion": "Ideal para hogares tranquilos y pacientes.",
        "tasaAdopcion": 90,
        "seEnvia": "Adopciones locales únicamente",
        "adoptionState": "Disponible"
    },
    {
        "especie": "Arácnido",
        "edad": "Adulto",
        "fechaDeNacimiento": "2019-05-10",
        "sexo": "Hembra",
        "tamaño": "Grande",
        "peso": 0.1,
        "vacunado": false,
        "desparasitado": false,
        "sano": true,
        "esterilizado": false,
        "identificado": true,
        "microchip": false,
        "nombre": "Tara",
        "image": "https://www.example.com/tara.jpg",
        "ubicacion": "Valencia",
        "ciudad": "Valencia",
        "personalidad": ["Calmada", "Reservada", "Curiosa"],
        "historia": "Rescatada de un entorno no adecuado, busca un nuevo hogar.",
        "aSaber": "Es una tarántula dócil pero necesita un cuidador con experiencia.",
        "requisitosAdopcion": "Solo para personas con experiencia en arácnidos.",
        "tasaAdopcion": 50,
        "seEnvia": "Adopciones locales únicamente",
        "adoptionState": "Disponible"
    },
    {
        "especie": "Reptil",
        "edad": "Adulto",
        "fechaDeNacimiento": "2017-08-25",
        "sexo": "Macho",
        "tamaño": "Mediano",
        "peso": 1.5,
        "vacunado": false,
        "desparasitado": false,
        "sano": true,
        "esterilizado": false,
        "identificado": true,
        "microchip": false,
        "nombre": "Spike",
        "image": "https://www.example.com/spike.jpg",
        "ubicacion": "Madrid",
        "ciudad": "Madrid",
        "personalidad": ["Tranquilo", "Observador", "Activo"],
        "historia": "Entregado por su dueño anterior, busca un hogar adecuado.",
        "aSaber": "Necesita un ambiente con temperaturas adecuadas y un terrario espacioso.",
        "requisitosAdopcion": "Solo para personas con experiencia en reptiles.",
        "tasaAdopcion": 80,
        "seEnvia": "Adopciones locales únicamente",
        "adoptionState": "Disponible"
    },
    {
        "especie": "Reptil",
        "edad": "Joven",
        "fechaDeNacimiento": "2020-12-01",
        "sexo": "Hembra",
        "tamaño": "Pequeño",
        "peso": 0.8,
        "vacunado": false,
        "desparasitado": false,
        "sano": true,
        "esterilizado": false,
        "identificado": true,
        "microchip": false,
        "nombre": "Ziggy",
        "image": "https://www.example.com/ziggy.jpg",
        "ubicacion": "Barcelona",
        "ciudad": "Barcelona",
        "personalidad": ["Curioso", "Activo", "Explorador"],
        "historia": "Entregado por su dueño anterior debido a cambios en las circunstancias.",
        "aSaber": "Necesita un terrario con áreas para trepar y esconderse.",
        "requisitosAdopcion": "Solo para personas con experiencia en reptiles.",
        "tasaAdopcion": 100,
        "seEnvia": "Adopciones locales únicamente",
        "adoptionState": "Disponible"
    },
    {
        "especie": "Tortuga",
        "edad": "Adulto",
        "fechaDeNacimiento": "2015-04-10",
        "sexo": "Hembra",
        "tamaño": "Pequeño",
        "peso": 0.5,
        "vacunado": false,
        "desparasitado": false,
        "sano": true,
        "esterilizado": false,
        "identificado": true,
        "microchip": false,
        "nombre": "Tina",
        "image": "https://www.example.com/tina.jpg",
        "ubicacion": "Sevilla",
        "ciudad": "Sevilla",
        "personalidad": ["Tranquila", "Exploradora", "Pacífica"],
        "historia": "Rescatada de un entorno inadecuado, busca un hogar donde pueda vivir feliz.",
        "aSaber": "Necesita un terrario con acceso a agua y tierra para caminar.",
        "requisitosAdopcion": "Solo para personas con experiencia en tortugas.",
        "tasaAdopcion": 70,
        "seEnvia": "Adopciones locales únicamente",
        "adoptionState": "Disponible"
    },
    {
        "especie": "Perro",
        "edad": "Adulto",
        "fechaDeNacimiento": "2016-10-08",
        "sexo": "Hembra",
        "tamaño": "Grande",
        "peso": 18,
        "vacunado": true,
        "desparasitado": true,
        "sano": true,
        "esterilizado": true,
        "identificado": true,
        "microchip": true,
        "nombre": "Coco",
        "image": "https://www.example.com/coco.jpg",
        "ubicacion": "Madrid",
        "ciudad": "Madrid",
        "personalidad": ["Amigable", "Tranquilo", "Leal"],
        "historia": "Rescatado de un refugio, busca un hogar permanente.",
        "aSaber": "Le encanta pasear y está bien entrenado.",
        "requisitosAdopcion": "Ideal para hogares con espacio al aire libre.",
        "tasaAdopcion": 200,
        "seEnvia": "Adopciones locales únicamente",
        "adoptionState": "Disponible"
    },
    {
        "especie": "Ave",
        "edad": "Adulto",
        "fechaDeNacimiento": "2018-07-12",
        "sexo": "Macho",
        "tamaño": "Pequeño",
        "peso": 0.4,
        "vacunado": true,
        "desparasitado": true,
        "sano": true,
        "esterilizado": false,
        "identificado": true,
        "microchip": false,
        "nombre": "Pipo",
        "image": "https://www.example.com/pipo.jpg",
        "ubicacion": "Valencia",
        "ciudad": "Valencia",
        "personalidad": ["Alegre", "Sociable", "Juguetón"],
        "historia": "Rescatado de una situación de abandono, busca un nuevo hogar.",
        "aSaber": "Le gusta cantar y estar en compañía.",
        "requisitosAdopcion": "Ideal para personas que puedan dedicarle tiempo y atención.",
        "tasaAdopcion": 100,
        "seEnvia": "Adopciones locales únicamente",
        "adoptionState": "Disponible"
    }
]

